name: planty
description: "Planty will simplify your plants irrigation by providing a user-friendly application that connects with your PlantyPot."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  intl: ^0.20.2
  provider: ^6.1.5+1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
